### ISSUE TITLE
Invalid magic word 'MAG_NOTINYMCE'

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#2]
At this moment MASTER is broken. The below error and trace is shown on every page:

```
[4dbe1f4eec2eece004030284] /mediawiki-1.27.4/index.php?title=Main_Page MWException from line 335 of C:\Apache\htdocs\mediawiki-1.27.4\includes\MagicWord.php: Error: invalid magic word 'MAG_NOTINYMCE'

Backtrace:

#0 C:\Apache\htdocs\mediawiki-1.27.4\includes\MagicWord.php(260): MagicWord->load(string)
#1 C:\Apache\htdocs\mediawiki-1.27.4\includes\MagicWordArray.php(78): MagicWord::get(string)
#2 C:\Apache\htdocs\mediawiki-1.27.4\includes\MagicWordArray.php(247): MagicWordArray->getHash()
#3 C:\Apache\htdocs\mediawiki-1.27.4\includes\parser\Parser.php(3526): MagicWordArray->matchStartToEnd(string)
#4 C:\Apache\htdocs\mediawiki-1.27.4\includes\parser\Preprocessor_DOM.php(1175): Parser->braceSubstitution(array, PPFrame_DOM)
#5 C:\Apache\htdocs\mediawiki-1.27.4\includes\parser\Parser.php(3380): PPFrame_DOM->expand(DOMElement, integer)
#6 C:\Apache\htdocs\mediawiki-1.27.4\includes\parser\Parser.php(665): Parser->replaceVariables(string, PPFrame_DOM)
#7 C:\Apache\htdocs\mediawiki-1.27.4\includes\parser\Parser.php(5120): Parser->preprocess(string, Title, ParserOptions)
#8 C:\Apache\htdocs\mediawiki-1.27.4\includes\cache\MessageCache.php(1041): Parser->transformMsg(string, ParserOptions, Title)
#9 C:\Apache\htdocs\mediawiki-1.27.4\includes\Message.php(1179): MessageCache->transform(string, boolean, Language, Title)
#10 C:\Apache\htdocs\mediawiki-1.27.4\includes\Message.php(829): Message->transformText(string)
#11 C:\Apache\htdocs\mediawiki-1.27.4\includes\Message.php(892): Message->toString()
#12 C:\Apache\htdocs\mediawiki-1.27.4\includes\OutputPage.php(927): Message->text()
#13 C:\Apache\htdocs\mediawiki-1.27.4\includes\OutputPage.php(974): OutputPage->setHTMLTitle(Message)
#14 C:\Apache\htdocs\mediawiki-1.27.4\includes\page\Article.php(509): OutputPage->setPageTitle(string)
#15 C:\Apache\htdocs\mediawiki-1.27.4\includes\actions\ViewAction.php(44): Article->view()
#16 C:\Apache\htdocs\mediawiki-1.27.4\includes\MediaWiki.php(493): ViewAction->show()
#17 C:\Apache\htdocs\mediawiki-1.27.4\includes\MediaWiki.php(288): MediaWiki->performAction(Article, Title)
#18 C:\Apache\htdocs\mediawiki-1.27.4\includes\MediaWiki.php(735): MediaWiki->performRequest()
#19 C:\Apache\htdocs\mediawiki-1.27.4\includes\MediaWiki.php(509): MediaWiki->main()
#20 C:\Apache\htdocs\mediawiki-1.27.4\index.php(43): MediaWiki->run()
#21 {main}
```

This happens in MW-1.27.4 1.29.2 & 1.30.0 (PHP 7.0.21)

**Comment by yaronkoren** [comment]
Oops, sorry about that! I forgot to check in the new file. I think this is fixed now.

**Comment by jongfeli** [comment]
Master works again.

`__NOTINYMCE__` also works. Thanks.
